### ISSUE TITLE
Icon search 

### ISSUE THREAD

**Issue by AAbubaker00** [kituyiharry/peek#4]
I'm confused on how you are able to retrieve the icons for the selected stock.

**Comment by kituyiharry** [comment]
Hey,

The app uses the [IEX logos endpoint](https://iexcloud.io/docs/api/#logo), However rather than doing a GET to get the URL from them I optimistically fetch it using their googleapis storage URL. Check line 374 at https://github.com/kituyiharry/peek/blob/c47f0a70545573a2f46bcdf02fae15667f1dbc4f/lib/main.dart#L374
